### ISSUE TITLE
Support all <angle> units in color functions

### ISSUE THREAD

**Issue by nex3** [sass/sass#2904]
- [x] [Proposal](https://github.com/sass/sass/blob/main/accepted/angle-units.md) (https://github.com/sass/sass/pull/2953)

**Phase 1**

- [x] [Specs](https://github.com/sass/sass-spec/issues/1607) (https://github.com/sass/sass-spec/pull/1608)
- [x] [Documentation](https://github.com/sass/sass-site/issues/511) (https://github.com/sass/sass-site/pull/512)
- [x] [Dart Sass](https://github.com/sass/dart-sass/issues/1174) (https://github.com/sass/dart-sass/pull/1175)
- [x] Update canonical spec (#2974)

**Phase 2**

- [x] [Specs](https://github.com/sass/sass-spec/issues/1607) (https://github.com/sass/sass-spec/pull/1831)
- [x] [Dart Sass](https://github.com/sass/dart-sass/issues/1174) (https://github.com/sass/dart-sass/pull/1818)
- [x] [Documentation](https://github.com/sass/sass-site/issues/511) (https://github.com/sass/sass-site/pull/683)

**Phase 3**

- [x] Spec (https://github.com/sass/sass/pull/4139)
- [x] [Tests](https://github.com/sass/sass-spec/issues/1607) (https://github.com/sass/sass-spec/pull/2088)
- [x] [Dart Sass](https://github.com/sass/dart-sass/issues/1174) (https://github.com/sass/dart-sass/pull/2656)
- [ ] [Documentation](https://github.com/sass/sass-site/issues/511)

---

Currently, Sass's color functions (including both the existing functions and the functions added by https://github.com/sass/sass/pull/2835) only support `deg` as a hue unit. CSS specifies, and browsers support, a [wider variety of units](https://www.w3.org/TR/css3-values/#angles), including `grad`, `rad`, and `turn`. We should support all these units, internally converting them to `deg`.

Because `hsl()`'s and `*-color()`'s `$hue` arguments currently accept *any* unit, not just a unitless number or `deg`, this will require an intermediate deprecation step where we forbid units other than `deg` for hue values. As part of this, we can also tighten up the unit requirements for `$saturation` and `$lightness` to require either no unit or `%`.

**Comment by nex3** [comment]
The proposal has landed, giving it two weeks for public comment.

**Comment by nex3** [comment]
This is now waiting on Dart Sass 2.0.0
