### ISSUE TITLE
Deprecate and remove meta.feature-exists()

### ISSUE THREAD

**Issue by nex3** [sass/sass#3702]
- [x] [Proposal](https://github.com/sass/sass/blob/main/accepted/remove-feature-exists.md) (https://github.com/sass/sass/pull/3749)
- **Deprecation**
  - [x] Update official spec (https://github.com/sass/sass/pull/3860)
  - [x] Dart Sass (https://github.com/sass/dart-sass/pull/2235/)
  - [x] Tests (https://github.com/sass/sass-spec/pull/1986)
  - [x] Website (https://github.com/sass/sass-site/pull/1148)
- **Removal**
  - [x] Update official spec (https://github.com/sass/sass/pull/4230)
  - [x] Dart Sass (https://github.com/sass/dart-sass/pull/2781)
  - [x] Tests (https://github.com/sass/sass-spec/pull/2141)
  - [ ] Website

---

From https://github.com/sass/sass-spec/issues/1939#issuecomment-1738040431: 

> In practice, essentially all the new features we add fall into one of three categories:
>
> 1. New built-in functions or mixins, which are easy to detect using other `sass:meta` functions.
> 2. Language-level features which are relatively easy to detect on their own (for example, first-class calc can be detected with `calc(1 + 1) == 2`).
> 3. New syntax which can't even be parsed in implementations that don't support it, for which feature detection isn't particularly useful anyway.

This, combined with the fact that we haven't added a new feature to `meta.feature-exists()` in years, suggests that it's not useful anymore and should be removed.

**Comment by nex3** [comment]
https://github.com/sass/sass/pull/3749 has landed and the proposal is out for review. Since it's a breaking change, I'll give it a month for public comment before we can mark it as accepted and implement.

**Comment by nex3** [comment]
@stof We just released 1.77.0, so these will need to be 1.78.0.

**Comment by stof** [comment]
@nex3 I updated all PRs to mention 1.78.0, and I also opened the missing PR for the website to document the deprecation.

**Comment by stof** [comment]
@nex3 how should all the PRs related to this be handled ? As they haven't been merged back then, they conflict again. I'd rather avoid doing more rebases if they get stuck in waiting time again.

**Comment by nex3** [comment]
I think the issue was that you never marked https://github.com/sass/dart-sass/pull/2235 for re-review after updating the changelog, so it got lost in the shuffle. Please go ahead and merge again, although since this was first put out we've changed deprecations to be centralized in [this file](https://github.com/sass/sass/blob/main/spec/deprecations.yaml) with everything else generated from that.

**Comment by stof** [comment]
> although since this was first put out we've changed deprecations to be centralized in [this file](https://github.com/sass/sass/blob/main/spec/deprecations.yaml) with everything else generated from that.

that's good news as it was quite painful to properly introduce a deprecation manually...

**Comment by stof** [comment]
@nex3 the PR to document the deprecation on the website also exists at https://github.com/sass/sass-site/pull/1049

**Comment by nex3** [comment]
Ah, sorry I missed it! I'll merge the two.
